---
# Ansible playbook for a GitLab server.
#
# @todo - Install postfix `yum -y install postfix`.
#
# @author Jeff Geerling (2014).

- hosts: gitlab
  gather_facts: yes

  vars_files:
    - vars/main.yml

  roles:
    - firewall
    - gitlab

  tasks:
    - name: gitlab backup
      cron: minute="20" 
            hour="10" 
            name="Gitlab backup"
            user="root"
            job="sudo tar -zcvf /etc/gitlab/backups/$(date "+backup-gitlab-\%s.tgz") -C /etc/gitlab"
